-- DROP TABLE
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE POSITION CASCADE CONSTRAINTS;
DROP TABLE WORK_STATUS CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE VACATION CASCADE CONSTRAINTS;
DROP TABLE OUTSIDE_WORK CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_TRIP CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;
DROP TABLE TODO CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_TRIP_FORM CASCADE CONSTRAINTS;
DROP TABLE PAY_FORM CASCADE CONSTRAINTS;
DROP TABLE VACATION_FORM CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE NOTICE_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE ORGAN CASCADE CONSTRAINTS;
DROP TABLE OPEN_DEPART CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;



-- DROP SEQUENCE 
DROP SEQUENCE SEQ_COMPANY_NO;
DROP SEQUENCE SEQ_DEPARTMENT_NO;
DROP SEQUENCE SEQ_AUTHORITY_NO;
DROP SEQUENCE SEQ_POSITION_NO;
DROP SEQUENCE SEQ_WORK_STATUS_NO;
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_SCHEDULE_NO;
DROP SEQUENCE SEQ_VACATION_NO;
DROP SEQUENCE SEQ_OUTSIDE_WORK_NO;
DROP SEQUENCE SEQ_BUSINESS_TRIP_NO;
DROP SEQUENCE SEQ_DOCUMENT_NO;
DROP SEQUENCE SEQ_TODO_NO;
DROP SEQUENCE SEQ_BUSINESS_TRIP_FORM_NO;
DROP SEQUENCE SEQ_PAY_FORM_NO;
DROP SEQUENCE SEQ_VACATION_FORM_NO;
DROP SEQUENCE SEQ_MESSAGE_NO;
DROP SEQUENCE SEQ_NOTICE_CATEGORY_NO;
DROP SEQUENCE SEQ_BOOK_NO;
DROP SEQUENCE SEQ_ORGAN_NO;
DROP SEQUENCE SEQ_OPEN_DEPART_NO;
DROP SEQUENCE SEQ_NOTICE_NO;


-- CREATE TABLE
CREATE TABLE POSITION (
	NO		NUMBER			PRIMARY KEY,
	NAME	VARCHAR2(20)	NULL
);

CREATE TABLE DEPARTMENT (
	NO		NUMBER			PRIMARY KEY,
	NAME	VARCHAR2(20)	NOT NULL,
	TEL		CHAR(11)		NULL
);

CREATE TABLE AUTHORITY (
	NO		NUMBER			PRIMARY KEY,
	NAME	VARCHAR2(12)	NOT NULL
);

CREATE TABLE MEMBER (
	NO				NUMBER				PRIMARY KEY,
	NAME			VARCHAR2(100)		NOT NULL,
	ID				VARCHAR2(30)		NOT NULL,
	PWD				VARCHAR2(30)		NOT NULL,
	EMAIL			VARCHAR2(30)		NOT NULL,
	TEL				CHAR(11)			NOT NULL,
	ADDRESS			VARCHAR2(50)		NOT NULL,
	ANNUAL			NUMBER				DEFAULT '0'	NOT NULL,
	AUTH_NO			NUMBER				NOT NULL,
	DEPART_NO		NUMBER				NOT NULL,
	COMPANY_NO		NUMBER				NOT NULL,
	POSITION_NO		NUMBER				NOT NULL,
	WORK_STATUS_NO	NUMBER				NOT NULL
);

CREATE TABLE COMPANY (
	NO			NUMBER				PRIMARY KEY,
	NAME		VARCHAR2(20)		NOT NULL,
	MANAGER_NO	NUMBER				NULL
);

CREATE TABLE WORK_STATUS (
	NO		NUMBER				PRIMARY KEY,
	STATUS	VARCHAR2(20)		NOT NULL
);

CREATE TABLE VACATION (
	NO				NUMBER		PRIMARY KEY,
	MEMBER_NO		NUMBER		NOT NULL,
	START_DATE		DATE		NOT NULL,
	END_DATE		DATE		NOT NULL,
	USED_DAYS		FLOAT		NOT NULL,
	HALF_DAY_TYPE	CHAR(4)		NULL
);

CREATE TABLE OUTSIDE_WORK (
	NO				NUMBER			PRIMARY KEY,
	MEMBER_NO		NUMBER			NOT NULL,
	START_TIME		TIMESTAMP		NOT NULL,
	END_TIME		TIMESTAMP		NOT NULL,
	ONSITE_START	CHAR(1)			NULL,
	ONSITE_END		CHAR(1)			NULL
);

CREATE TABLE BUSINESS_TRIP (
	NO			NUMBER				PRIMARY KEY,
	MEMBER_NO	NUMBER				NOT NULL,
	START_DATE	DATE				NOT NULL,
	END_DATE	DATE				NOT NULL,
	MEMO		VARCHAR2(100)		NULL
);

CREATE TABLE SCHEDULE (
	NO				NUMBER				PRIMARY KEY,
	TITLE			VARCHAR2(100)		NOT NULL,
	CONTENT			VARCHAR2(300)		NOT NULL,
	START_TIME		TIMESTAMP			NOT NULL,
	END_TIME		TIMESTAMP			NOT NULL,
	ALL_DEPART_YN	CHAR(1)				NOT NULL,
	DEPART_NO		NUMBER				NULL,
	MEMBER_NO		NUMBER				NOT NULL
);

CREATE TABLE DOCUMENT (
   NO      			NUMBER         		PRIMARY KEY,
   MEMBER_NO   		NUMBER         		NOT NULL,
   WRITE_DATE   	TIMESTAMP      		NOT NULL,
   FIRST_APPLY_NO   NUMBER      	    NOT NULL,
   MID_APPLY_NO   	NUMBER      	    NOT NULL,
   LAST_APPLY_NO   	NUMBER      	    NOT NULL,
   APPLY_DATE   	TIMESTAMP      		NOT NULL,
   STATUS      		CHAR(1)         	NOT NULL,
   DOCUMENT_MENU   	VARCHAR2(100)      	NOT NULL,
   REASON      		VARCHAR2(1000)      NOT NULL
);

-- TODO 테이블;
CREATE TABLE TODO (
   NO      			NUMBER         		PRIMARY KEY,
   MEMBER_NO   		NUMBER      		NOT NULL,
   CONTENT      	VARCHAR2(1000)   	NOT NULL,
   WRITE_DATE   	TIMESTAMP   		NOT NULL,
   MODIFY_DATE   	TIMESTAMP   		NULL,
   DELETE_DATE   	TIMESTAMP   		NULL,
   DEL_YN      		CHAR(1)      		NOT NULL
);

--쪽지 테이블
CREATE TABLE MESSAGE ( 
   NO      			NUMBER      	PRIMARY KEY,
   SEND_NO      	NUMBER      	NOT NULL,
   RECIEVE_NO   	NUMBER      	NOT NULL,
   CONTENT      	VARCHAR2(1000)  NOT NULL,
   SEND_DATE   		TIMESTAMP   	NOT NULL,
   DELETE_DATE   	TIMESTAMP   	NULL,
   STATUS      		CHAR(1)      	NOT NULL
);

--휴가신청서 테이블
CREATE TABLE VACATION_FORM (
   NO      		NUMBER      	PRIMARY KEY,
   DOCUMENT_NO  NUMBER      	NOT NULL,
   CATEGORY   	VARCHAR2(100)   NOT NULL,
   START_TIME   TIMESTAMP   	NOT NULL,
   FINISH_TIME  TIMESTAMP   	NOT NULL,
   CONTENT      VARCHAR2(100)   NOT NULL,
   DEL_YN      	CHAR(1)      	NOT NULL,
   STATUS      	CHAR(1)      	NOT NULL
);

--출장신청서 테이블
CREATE TABLE BUSINESS_TRIP_FORM (
   NO      			NUMBER      	PRIMARY KEY,
   DOCUMENT_NO  	NUMBER      	NOT NULL,
   START_TIME      	TIMESTAMP   	NULL,
   FINISH_TIME      TIMESTAMP   	NULL,
   CONTENT     		VARCHAR2(100)   NULL,
   DEL_YN      		CHAR(1)      	NULL,
   STATUS      		CHAR(1)      	NULL
);

--지출결의서 테이블
CREATE TABLE PAY_FORM (
   NO      			NUMBER     			PRIMARY KEY,
   DOCUMENT_NO   	NUMBER        		NOT NULL,
   DEADLINE   		TIMESTAMP      		NOT NULL,
   CATEGORY   		VARCHAR2(100)      	NOT NULL,
   TITLE      		VARCHAR2(100)      	NOT NULL,
   DETAIL      		VARCHAR2(100)      	NOT NULL,
   AMOUNT      		VARCHAR2(100)      	NOT NULL,
   REFFERENCE   	VARCHAR2(100)      	NOT NULL,
   STATUS      		CHAR(1)         	NOT NULL,
   ALLAMOUNT   		VARCHAR2(100)      	NOT NULL,
   MONETARY_UNIT   	VARCHAR2(100)      	NOT NULL,
   DEL_YN      		CHAR(1)         	NOT NULL
);

CREATE TABLE NOTICE_CATEGORY (
	CATEGORY_NO	NUMBER		PRIMARY KEY,
	NOTICE_NO	NUMBER		NOT NULL
);

CREATE TABLE BOOK (
	BOOK_NO			NUMBER				PRIMARY KEY,
	MEMBER_NO		NUMBER				NOT NULL,
	USE_DATE		TIMESTAMP			NOT NULL,
	BOOK_PURPOSE	VARCHAR2(1000)		NOT NULL,
	BOOK_DATE		TIMESTAMP			NOT NULL,
	UPDATE_DATE		TIMESTAMP			NULL,
	CANCEL_DATE		TIMESTAMP			NULL
);

CREATE TABLE ORGAN (
	ORG_NO		NUMBER				PRIMARY KEY,
	MEMBER_NO	NUMBER				NOT NULL,
	PROFILE		VARCHAR2(1000)		NOT NULL,
	DEPARTMENT	NUMBER				NOT NULL,
	POSITION	NUMBER				NOT NULL,
	NAME		VARCHAR2(100)		NOT NULL,
	TEL			CHAR(11)			NOT NULL
);

CREATE TABLE OPEN_DEPART (
	OPEN_NO		NUMBER		PRIMARY KEY,
	DEPART_NO	NUMBER		NOT NULL,
	NOTICE_NO	NUMBER		NOT NULL
);

CREATE TABLE NOTICE (
	NOTICE_NO		NUMBER								PRIMARY KEY,
	MEMBER_NO		NUMBER								NOT NULL,
	TITLE			VARCHAR2(100)						NOT NULL,
	CONTENT			VARCHAR2(4000)						NOT NULL,
	CLICK_NO		NUMBER			DEFAULT '0'			NULL,
	FILE_PATH		VARCHAR2(1000)						NULL,
	CATEGORY		NUMBER								NOT NULL,
	EMERGENCY_YN	CHAR(1)			DEFAULT 'N'			NOT NULL,
	OPEN_DEPART		NUMBER								NOT NULL,
	ENROLL_DATE		TIMESTAMP		DEFAULT SYSDATE		NOT NULL,
	UPDATE_DATE		TIMESTAMP							NULL,
	DELETE_YN		CHAR(1)			DEFAULT 'N'			NULL
);

-- CREATE SEQUENCE
CREATE SEQUENCE SEQ_COMPANY_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DEPARTMENT_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 100 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AUTHORITY_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 5 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_POSITION_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 100 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_WORK_STATUS_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 10 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_VACATION_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_OUTSIDE_WORK_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BUSINESS_TRIP_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DOCUMENT_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_TODO_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_BUSINESS_TRIP_FORM_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_PAY_FORM_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_VACATION_FORM_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_MESSAGE_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE; 
CREATE SEQUENCE SEQ_NOTICE_CATEGORY_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 50 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BOOK_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ORGAN_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 100 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_OPEN_DEPART_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 1000 NOCYCLE NOCACHE;

-- FK
ALTER TABLE MEMBER 
ADD CONSTRAINT FK_AUTHORITY_MEMBER FOREIGN KEY (AUTH_NO) REFERENCES AUTHORITY (NO);

ALTER TABLE MEMBER 
ADD CONSTRAINT FK_DEPARTMENT_MEMBER FOREIGN KEY (DEPART_NO) REFERENCES DEPARTMENT (NO);

ALTER TABLE MEMBER 
ADD CONSTRAINT FK_COMPANY_MEMBER FOREIGN KEY (COMPANY_NO) REFERENCES COMPANY (NO);

ALTER TABLE MEMBER 
ADD CONSTRAINT FK_POSITION_MEMBER FOREIGN KEY (POSITION_NO) REFERENCES POSITION (NO);

ALTER TABLE MEMBER 
ADD CONSTRAINT FK_WORK_STATUS_MEMBER FOREIGN KEY (WORK_STATUS_NO) REFERENCES WORK_STATUS (NO);

ALTER TABLE VACATION 
ADD CONSTRAINT FK_MEMBER_VACATION FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE OUTSIDE_WORK 
ADD CONSTRAINT FK_MEMBER_OUTSIDE_WORK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE BUSINESS_TRIP 
ADD CONSTRAINT FK_MEMBER_BUSINESS_TRIP FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE SCHEDULE 
ADD CONSTRAINT FK_DEPARTMENT_SCHEDULE FOREIGN KEY (DEPART_NO) REFERENCES DEPARTMENT (NO);

ALTER TABLE SCHEDULE 
ADD CONSTRAINT FK_MEMBER_SCHEDULE FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_FIRST_APPLY_NO FOREIGN KEY (FIRST_APPLY_NO) REFERENCES MEMBER (NO);

ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_MID_APPLY_NO FOREIGN KEY (MID_APPLY_NO) REFERENCES MEMBER (NO);

ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_LAST_APPLY_NO FOREIGN KEY (LAST_APPLY_NO) REFERENCES MEMBER (NO);

ALTER TABLE TODO
ADD CONSTRAINT FK_TODO_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE MESSAGE
ADD CONSTRAINT FK_MESSAGE_MEMBER FOREIGN KEY (SEND_NO) REFERENCES MEMBER (NO);

ALTER TABLE MESSAGE
ADD CONSTRAINT FK_RECIEVE_NO FOREIGN KEY (RECIEVE_NO) REFERENCES MEMBER (NO);

ALTER TABLE PAY_FORM
ADD CONSTRAINT FK_DOCUMENT_NO FOREIGN KEY (DOCUMENT_NO) REFERENCES DOCUMENT (NO);

ALTER TABLE BUSINESS_TRIP_FORM
ADD CONSTRAINT FK_B_FORM_DOCUMENT FOREIGN KEY (DOCUMENT_NO) REFERENCES DOCUMENT (NO);

ALTER TABLE VACATION_FORM
ADD CONSTRAINT FK_V_FORM_DOCUMENT FOREIGN KEY (DOCUMENT_NO) REFERENCES DOCUMENT (NO);

ALTER TABLE NOTICE_CATEGORY 
ADD CONSTRAINT FK_NOTICE_NOTICE_CATEGORY FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE (NOTICE_NO);

ALTER TABLE BOOK 
ADD CONSTRAINT FK_MEMBER_BOOK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE ORGAN 
ADD CONSTRAINT FK_MEMBER_ORGAN FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);

ALTER TABLE OPEN_DEPART 
ADD CONSTRAINT FK_DEPARTMENT_OPEN_DEPART FOREIGN KEY (DEPART_NO) REFERENCES DEPARTMENT (NO);

ALTER TABLE OPEN_DEPART 
ADD CONSTRAINT FK_NOTICE_OPEN_DEPART FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE (NOTICE_NO);

ALTER TABLE NOTICE 
ADD CONSTRAINT FK_MEMBER_NOTICE FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO);
